# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
        - "*"
        - "!main"
  pull_request:
    branches:
        - "*"
        - "!main"

jobs:
        
  build:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v3
    - name: Test environment for MySQL
      uses: jordiprats/mysql-action@1.1
      with:
        mysql version: 8
        mysql root password: SPESM1234   
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
